services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  grpc-service:
    build: ./grpc-service
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: itemsdb
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "50051:50051"


  rest-service:
    build: ./rest-service
    depends_on:
      - grpc-service
    ports:
      - "5000:5000"
    environment:
      GRPC_HOST: grpc-service
      GRPC_PORT: 50051


volumes:
  mongo-data: