# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myitems.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'myitems.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyitems.proto\x12\x07myitems\" \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"D\n\x0f\x41\x64\x64ItemResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12!\n\nadded_item\x18\x02 \x01(\x0b\x32\r.myitems.Item\"H\n\x0fGetItemResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12%\n\x0erequested_item\x18\x02 \x01(\x0b\x32\r.myitems.Item\"f\n\x12UpdateItemResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x1f\n\x08old_item\x18\x02 \x01(\x0b\x32\r.myitems.Item\x12\x1f\n\x08new_item\x18\x03 \x01(\x0b\x32\r.myitems.Item\"I\n\x12\x44\x65leteItemResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12#\n\x0c\x64\x65leted_item\x18\x02 \x01(\x0b\x32\r.myitems.Item2\xeb\x01\n\x0bItemService\x12\x32\n\x07\x41\x64\x64Item\x12\r.myitems.Item\x1a\x18.myitems.AddItemResponse\x12\x34\n\x07GetItem\x12\r.myitems.Item\x1a\x18.myitems.GetItemResponse0\x01\x12\x38\n\nUpdateItem\x12\r.myitems.Item\x1a\x1b.myitems.UpdateItemResponse\x12\x38\n\nDeleteItem\x12\r.myitems.Item\x1a\x1b.myitems.DeleteItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myitems_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=26
  _globals['_ITEM']._serialized_end=58
  _globals['_ADDITEMRESPONSE']._serialized_start=60
  _globals['_ADDITEMRESPONSE']._serialized_end=128
  _globals['_GETITEMRESPONSE']._serialized_start=130
  _globals['_GETITEMRESPONSE']._serialized_end=202
  _globals['_UPDATEITEMRESPONSE']._serialized_start=204
  _globals['_UPDATEITEMRESPONSE']._serialized_end=306
  _globals['_DELETEITEMRESPONSE']._serialized_start=308
  _globals['_DELETEITEMRESPONSE']._serialized_end=381
  _globals['_ITEMSERVICE']._serialized_start=384
  _globals['_ITEMSERVICE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
